Traceback (most recent call last):
  File "/home/programma/mysite/programs/2023_07_03_06_42_23_009898.py", line 5, in <module>
    for _n, _v in globals().items():
RuntimeError: dictionary changed size during iteration
