Traceback (most recent call last):
  File "/home/programma/mysite/programs/2023_07_03_06_45_01_129980.py", line 6, in <module>
    for _n, _v in _global_vars.items():
RuntimeError: dictionary changed size during iteration
